#include "controller.h"
#include "imageitem.h"
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQuickStyle>
#include <QQuickWindow>
#include <QTest>
#include <QJsonDocument>
#include <QJsonObject>
#include <QDir>
#include <QFile>
#include <QElapsedTimer>
#include <QTextStream>
#include <functional>
using namespace piclens;
bool waitFor(std::function<bool()> f,int ms=8000){QElapsedTimer t;t.start();while(!f()&&t.elapsed()<ms){QCoreApplication::processEvents();QThread::msleep(5);}return f();}
QByteArray read(QString p){QFile f(p);if(!f.open(QIODevice::ReadOnly))return {};return f.readAll();}
void put(QString p,QByteArray b="flag"){QFile f(p);if(f.open(QIODevice::WriteOnly))f.write(b);}
int main(int argc,char**argv){if(argc>1&&QByteArray(argv[1])=="--stall"){QCoreApplication app(argc,argv);return app.exec();}QGuiApplication app(argc,argv);QQuickStyle::setStyle("Basic");qmlRegisterType<ImageItem>("PicLens.Native",1,0,"ImageItem");QString root=app.arguments()[1],worker=app.arguments()[2],library=root+"/images";QDir().mkpath(library);for(auto name:{"a","b","c"}){QImage im(64,48,QImage::Format_RGBA8888);im.fill(Qt::green);if(!im.save(library+"/"+name+".png"))return 2;}
 QString wrapper=root+"/wrapper";QByteArray script=("#!/bin/sh\nprintf '%s|%s|%s\\n' \"$1\" \"$2\" \"$3\" >> '"+root+"/calls'\nif [ \"$1\" = --encode-temp ] && [ -e '"+root+"/stall-encode' ]; then printf '%s' \"$$\" > '"+root+"/encoder.pid'; exec '"+app.applicationFilePath()+"' --stall; fi\nif [ -e '"+root+"/fail-preview' ] && [ \"$2\" = '"+library+"/a.png' ] && [ \"$3\" = 1024 ]; then exit 41; fi\nif [ -e '"+root+"/fail-full' ] && [ \"$2\" = '"+library+"/b.png' ] && [ \"$3\" = 0 ]; then exit 42; fi\nexec '"+worker+"' \"$@\"\n").toUtf8();put(wrapper,script);QFile::setPermissions(wrapper,QFileDevice::ReadOwner|QFileDevice::WriteOwner|QFileDevice::ExeOwner);
 auto *provider=new ThumbProvider;Controller c(root+"/profile",wrapper,provider);QQmlApplicationEngine engine;engine.addImageProvider("thumb",provider);engine.rootContext()->setContextProperty("app",&c);engine.rootContext()->setContextProperty("launchWidth",900);engine.rootContext()->setContextProperty("launchHeight",700);engine.rootContext()->setContextProperty("showComponents",false);engine.load(QUrl("qrc:/qml/Main.qml"));if(engine.rootObjects().isEmpty())return 2;auto*w=qobject_cast<QQuickWindow*>(engine.rootObjects()[0]);if(!QTest::qWaitForWindowExposed(w))return 2;auto*item=w->findChild<ImageItem*>();if(!item)return 2;c.start(library);if(!waitFor([&]{return c.count()==3;}))return 2;
 put(root+"/fail-preview");put(root+"/fail-full");c.openViewer(0);bool fallback=waitFor([&]{return item->frame()&&item->frame()->edge==0&&item->frame()->path==library+"/a.png";});c.viewerStep(1);bool retained=waitFor([&]{return !c.viewerError().isEmpty()&&item->frame()&&item->frame()->edge==1024&&item->frame()->path==library+"/b.png";});c.closeViewer();QFile::remove(root+"/fail-preview");QFile::remove(root+"/fail-full");put(root+"/calls",{});c.openViewer(1);bool prefetched=waitFor([&]{return read(root+"/calls").count("--decode")==4&&item->frame()&&item->frame()->edge==0;});auto calls=read(root+"/calls").trimmed().split('\n');bool order=calls.size()==4&&calls[0].endsWith("b.png|1024")&&calls[1].endsWith("b.png|0")&&calls[2].endsWith("c.png|1024")&&calls[3].endsWith("a.png|1024");c.closeViewer();c.setSearch("a.png");if(!waitFor([&]{return c.count()==1;}))return 2;c.select(0,0);
 QFile::setPermissions(library,QFileDevice::ReadOwner|QFileDevice::ExeOwner);c.requestOperation("rename","blocked");bool failureReported=waitFor([&]{return c.property("toastOpen").toBool();});QFile::setPermissions(library,QFileDevice::ReadOwner|QFileDevice::WriteOwner|QFileDevice::ExeOwner);bool toast12=false;for(auto*obj:w->findChildren<QObject*>())if(obj->property("interval").toInt()==12000)toast12=true;bool failedResult=failureReported&&c.results().size()==1&&c.results()[0].toMap().value("status")==QStringLiteral("失敗")&&QFile::exists(library+"/a.png")&&!QFile::exists(library+"/blocked.png");
 put(root+"/stall-encode");QTest::qWait(150);const auto beforeStatus=c.status();const bool beforeBusy=c.busy();const bool beforeConfirm=c.confirmOpen();c.requestOperation("jpg");bool encoderStarted=waitFor([&]{return !read(root+"/encoder.pid").isEmpty();});QByteArray pid=read(root+"/encoder.pid");QElapsedTimer shutdown;shutdown.start();c.shutdown();auto shutdownMs=shutdown.elapsed();bool encoderReaped=!pid.isEmpty()&&!QFile::exists("/proc/"+QString::fromUtf8(pid)+"/stat");bool clean=QDir(library).entryList({".piclens-*"},QDir::Files|QDir::Hidden).isEmpty()&&!QFile::exists(library+"/a.jpg")&&QFile::exists(library+"/a.png");
 QJsonObject result{{"previewFailureStillLoadsOriginal",fallback},{"fullFailureKeepsPreview",retained},{"adjacentPreloadsComplete",prefetched},{"currentFullThenNextPreviousPreviewOrder",order},{"permissionFailureResultAndSourcePreserved",failedResult},{"failureToastTimerMilliseconds",toast12?12000:0},{"beforeBatchStatus",beforeStatus},{"beforeBatchBusy",beforeBusy},{"beforeBatchConfirm",beforeConfirm},{"afterBatchStatus",c.status()},{"encoderStarted",encoderStarted},{"shutdownMilliseconds",shutdownMs},{"encoderReaped",encoderReaped},{"canceledBatchTemporaryCleanAndSourcePreserved",clean}};QTextStream(stdout)<<QJsonDocument(result).toJson();return fallback&&retained&&prefetched&&order&&failedResult&&toast12&&encoderStarted&&encoderReaped&&clean&&shutdownMs<5000?0:1;}
