#include "controller.h"
#include "imageitem.h"
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQuickStyle>
#include <QQuickWindow>
#include <QTest>
#include <QJsonDocument>
#include <QJsonObject>
#include <QDir>
#include <QFile>
#include <QElapsedTimer>
#include <QTextStream>
#include <functional>
using namespace piclens;
bool waitFor(std::function<bool()> f,int ms=8000){QElapsedTimer t;t.start();while(!f()&&t.elapsed()<ms){QCoreApplication::processEvents();QThread::msleep(5);}return f();}
QByteArray read(QString p){QFile f(p);if(!f.open(QIODevice::ReadOnly))return {};return f.readAll();}
void put(QString p,QByteArray b="flag"){QFile f(p);if(f.open(QIODevice::WriteOnly))f.write(b);}
int main(int argc,char**argv){if(argc>1&&QByteArray(argv[1])=="--stall"){QCoreApplication app(argc,argv);return app.exec();}QGuiApplication app(argc,argv);QQuickStyle::setStyle("Basic");qmlRegisterType<ImageItem>("PicLens.Native",1,0,"ImageItem");QString root=app.arguments()[1],worker=app.arguments()[2],library=root+"/images";QDir().mkpath(library);for(auto name:{"a","b","c"}){QImage im(64,48,QImage::Format_RGBA8888);im.fill(Qt::green);if(!im.save(library+"/"+name+".png"))return 2;}
 QString wrapper=root+"/wrapper";QByteArray script=("#!/bin/sh\nprintf '%s|%s|%s\\n' \"$1\" \"$2\" \"$3\" >> '"+root+"/calls'\nif [ \"$1\" = --encode-temp ] && [ -e '"+root+"/stall-encode' ]; then printf '%s' \"$$\" > '"+root+"/encoder.pid'; exec '"+app.applicationFilePath()+"' --stall; fi\nif [ -e '"+root+"/fail-preview' ] && [ \"$2\" = '"+library+"/a.png' ] && [ \"$3\" = 1024 ]; then exit 41; fi\nif [ -e '"+root+"/fail-full' ] && [ \"$2\" = '"+library+"/b.png' ] && [ \"$3\" = 0 ]; then exit 42; fi\nexec '"+worker+"' \"$@\"\n").toUtf8();put(wrapper,script);QFile::setPermissions(wrapper,QFileDevice::ReadOwner|QFileDevice::WriteOwner|QFileDevice::ExeOwner);
 auto *provider=new ThumbProvider;Controller c(root+"/profile",wrapper,provider);QQmlApplicationEngine engine;engine.addImageProvider("thumb",provider);engine.rootContext()->setContextProperty("app",&c);engine.rootContext()->setContextProperty("launchWidth",900);engine.rootContext()->setContextProperty("launchHeight",700);engine.rootContext()->setContextProperty("showComponents",false);engine.load(QUrl("qrc:/qml/Main.qml"));if(engine.rootObjects().isEmpty())return 2;auto*w=qobject_cast<QQuickWindow*>(engine.rootObjects()[0]);if(!QTest::qWaitForWindowExposed(w))return 2;auto*item=w->findChild<ImageItem*>();if(!item)return 2;c.start(library);if(!waitFor([&]{return c.count()==3;}))return 2;
 
 w->requestActivate();QTest::qWaitForWindowActive(w);
 std::function<QQuickItem*(QQuickItem*,QString)> tileFor=[&](QQuickItem*i,QString path)->QQuickItem*{if(i->property("pooled").isValid()&&i->property("path")==path)return i;for(auto*child:i->childItems())if(auto*found=tileFor(child,path))return found;return nullptr;};QQuickItem*sourceTile=nullptr,*targetTile=nullptr;waitFor([&]{sourceTile=tileFor(w->contentItem(),library+"/a.png");targetTile=tileFor(w->contentItem(),library+"/b.png");return sourceTile&&targetTile;});bool dropReached=false,highlighted=false,dropPreview=false,dropCancelSafe=false;
 if(sourceTile&&targetTile){c.select(0,0);c.select(2,Qt::ControlModifier);auto center=[](QQuickItem*i){return i->mapToScene({i->width()/2,i->height()/2}).toPoint();};auto from=center(sourceTile),to=center(targetTile);QTest::mousePress(w,Qt::LeftButton,Qt::NoModifier,from);QTest::mouseMove(w,from+QPoint(32,32));QTest::qWait(30);QTest::mouseMove(w,to);QTest::qWait(100);for(auto*obj:targetTile->findChildren<QObject*>())if(obj->property("containsDrag").toBool())highlighted=true;QTest::mouseRelease(w,Qt::LeftButton,Qt::NoModifier,to);dropReached=waitFor([&]{return c.confirmOpen();},1500);if(dropReached){dropPreview=c.confirmText().contains("b-01.png")&&c.confirmText().contains("b-02.png");c.confirm(false);}dropCancelSafe=QFile::exists(library+"/a.png")&&QFile::exists(library+"/c.png")&&!QFile::exists(library+"/b-01.png");c.clearSelection();}
 put(root+"/fail-preview");put(root+"/fail-full");c.openViewer(0);bool fallback=waitFor([&]{return item->frame()&&item->frame()->edge==0&&item->frame()->path==library+"/a.png";});c.viewerStep(1);bool retained=waitFor([&]{return !c.viewerError().isEmpty()&&item->frame()&&item->frame()->edge==1024&&item->frame()->path==library+"/b.png";});c.closeViewer();QFile::remove(root+"/fail-preview");QFile::remove(root+"/fail-full");put(root+"/calls",{});c.openViewer(1);bool prefetched=waitFor([&]{return read(root+"/calls").count("--decode")==4&&item->frame()&&item->frame()->edge==0;});auto calls=read(root+"/calls").trimmed().split('\n');bool order=calls.size()==4&&calls[0].endsWith("b.png|1024")&&calls[1].endsWith("b.png|0")&&calls[2].endsWith("c.png|1024")&&calls[3].endsWith("a.png|1024");c.closeViewer();c.setSearch("a.png");if(!waitFor([&]{return c.count()==1;}))return 2;c.select(0,0);
 QFile::setPermissions(library,QFileDevice::ReadOwner|QFileDevice::ExeOwner);c.requestOperation("rename","blocked");bool failureReported=waitFor([&]{return c.property("toastOpen").toBool();});QFile::setPermissions(library,QFileDevice::ReadOwner|QFileDevice::WriteOwner|QFileDevice::ExeOwner);bool toast12=false;for(auto*obj:w->findChildren<QObject*>())if(obj->property("interval").toInt()==12000)toast12=true;bool failedResult=failureReported&&c.results().size()==1&&c.results()[0].toMap().value("status")==QStringLiteral("失敗")&&QFile::exists(library+"/a.png")&&!QFile::exists(library+"/blocked.png");
 put(root+"/stall-encode");QTest::qWait(150);const auto beforeStatus=c.status();const bool beforeBusy=c.busy();const bool beforeConfirm=c.confirmOpen();c.requestOperation("jpg");bool encoderStarted=waitFor([&]{return !read(root+"/encoder.pid").isEmpty();});QByteArray pid=read(root+"/encoder.pid");QElapsedTimer shutdown;shutdown.start();c.shutdown();auto shutdownMs=shutdown.elapsed();bool encoderReaped=!pid.isEmpty()&&!QFile::exists("/proc/"+QString::fromUtf8(pid)+"/stat");bool clean=QDir(library).entryList({".piclens-*"},QDir::Files|QDir::Hidden).isEmpty()&&!QFile::exists(library+"/a.jpg")&&QFile::exists(library+"/a.png");
 QJsonObject result{{"dropTargetHighlighted",highlighted},{"dropReachedConfirmation",dropReached},{"dropPreviewSmallestAvailableNames",dropPreview},{"dropCancelPreservesSources",dropCancelSafe},{"previewFailureStillLoadsOriginal",fallback},{"fullFailureKeepsPreview",retained},{"adjacentPreloadsComplete",prefetched},{"currentFullThenNextPreviousPreviewOrder",order},{"permissionFailureResultAndSourcePreserved",failedResult},{"failureToastTimerMilliseconds",toast12?12000:0},{"beforeBatchStatus",beforeStatus},{"beforeBatchBusy",beforeBusy},{"beforeBatchConfirm",beforeConfirm},{"afterBatchStatus",c.status()},{"encoderStarted",encoderStarted},{"shutdownMilliseconds",shutdownMs},{"encoderReaped",encoderReaped},{"canceledBatchTemporaryCleanAndSourcePreserved",clean}};
 QString navRoot=root+"/navigation";QDir().mkpath(navRoot+"/A/A1");QDir().mkpath(navRoot+"/B");auto*p2=new ThumbProvider;Controller nav(root+"/nav-profile",worker,p2);QQmlApplicationEngine e2;e2.addImageProvider("thumb",p2);e2.rootContext()->setContextProperty("app",&nav);e2.rootContext()->setContextProperty("launchWidth",900);e2.rootContext()->setContextProperty("launchHeight",700);e2.rootContext()->setContextProperty("showComponents",false);e2.load(QUrl("qrc:/qml/Main.qml"));auto*w2=qobject_cast<QQuickWindow*>(e2.rootObjects().value(0));if(!w2)return 2;QTest::qWaitForWindowExposed(w2);w2->requestActivate();QTest::qWaitForWindowActive(w2);nav.pick(QUrl::fromLocalFile(navRoot));
 std::function<QQuickItem*(QQuickItem*,QString)> hintItem=[&](QQuickItem*i,QString hint)->QQuickItem*{if(i->property("hint")==hint)return i;for(auto*child:i->childItems())if(auto*found=hintItem(child,hint))return found;return nullptr;};auto clickHint=[&](QString hint){QQuickItem*i=nullptr;if(!waitFor([&]{i=hintItem(w2->contentItem(),hint);return i&&i->isVisible();}))return false;QTest::mouseClick(w2,Qt::LeftButton,Qt::NoModifier,i->mapToScene({i->width()/2,i->height()/2}).toPoint());return true;};
 bool navReady=waitFor([&]{return nav.count()==2&&nav.tree()->rowCount()==2;});bool expanded=clickHint("展開 A")&&waitFor([&]{return nav.tree()->rowCount()==3;});bool collapsed=clickHint("收合 A")&&waitFor([&]{return nav.tree()->rowCount()==2;});bool reexpanded=clickHint("展開 A")&&waitFor([&]{return nav.tree()->rowCount()==3;});bool treeNavigation=clickHint(navRoot+"/A")&&waitFor([&]{return nav.folder()==navRoot+"/A";});
 QTest::mouseClick(w2,Qt::BackButton,Qt::NoModifier,{w2->width()/2,w2->height()/2});bool sideBack=waitFor([&]{return nav.folder()==navRoot;});QTest::mouseClick(w2,Qt::ForwardButton,Qt::NoModifier,{w2->width()/2,w2->height()/2});bool sideForward=waitFor([&]{return nav.folder()==navRoot+"/A";});nav.history(-1);waitFor([&]{return nav.folder()==navRoot&&nav.count()==2;});
 std::function<QQuickItem*(QQuickItem*)> findB=[&](QQuickItem*i)->QQuickItem*{if(i->property("pooled").isValid()&&i->property("path")==navRoot+"/B")return i;for(auto*child:i->childItems())if(auto*found=findB(child))return found;return nullptr;};QQuickItem*bTile=nullptr;waitFor([&]{bTile=findB(w2->contentItem());return bTile;});bool card=false;if(bTile){QTest::mouseClick(w2,Qt::LeftButton,Qt::NoModifier,bTile->mapToScene({bTile->width()/2,bTile->height()/2}).toPoint());card=waitFor([&]{return nav.folder()==navRoot+"/B";});}
 QImage refreshImage(2,2,QImage::Format_RGB32);refreshImage.fill(Qt::blue);refreshImage.save(navRoot+"/B/refresh.png");QTest::keyClick(w2,Qt::Key_F5);bool refreshed=waitFor([&]{return nav.count()==1;});nav.select(0,0);nav.setSortIndex(1);nav.setRecursive(true);nav.navigate(navRoot+"/A");nav.navigate(navRoot+"/B");bool staleCleared=waitFor([&]{return nav.folder()==navRoot+"/B"&&nav.count()==1&&nav.selectionCount()==0;});bool fixedRoot=nav.rootPath()==navRoot&&nav.tree()->rowCount()==3;nav.shutdown();bool persisted=readProfile(root+"/nav-profile").settings.value("lastFolderPath").toString()==navRoot;
 bool navigation=navReady&&expanded&&collapsed&&reexpanded&&treeNavigation&&sideBack&&sideForward&&card&&refreshed&&staleCleared&&fixedRoot&&persisted;result.insert("navigation",QJsonObject{{"rootReady",navReady},{"expanded",expanded},{"collapsed",collapsed},{"reexpanded",reexpanded},{"treeNavigation",treeNavigation},{"sideBack",sideBack},{"sideForward",sideForward},{"folderCard",card},{"refresh",refreshed},{"staleSelectionCleared",staleCleared},{"rootAndTopLevelStable",fixedRoot},{"persistedPickerPathUnchanged",persisted}});
 QTextStream(stdout)<<QJsonDocument(result).toJson();return fallback&&retained&&prefetched&&order&&failedResult&&toast12&&encoderStarted&&encoderReaped&&clean&&shutdownMs<5000&&navigation?0:1;}

